import streamlit as st
from g4f.client import Client
from fpdf import FPDF
import datetime

# --- 1. إعدادات الصفحة والواجهة السيبرانية ---
st.set_page_config(page_title="Cyber Guard Pro", page_icon="🛡️", layout="wide")

# تصميم واجهة الـ Hacker Mode
st.markdown("""
    <style>
    .stApp { background-color: #0d1117; color: #00ff41; }
    .dev-name { 
        text-align: center; font-family: 'Courier New'; color: #00ff41; 
        border-bottom: 2px solid #00ff41; padding: 10px; text-shadow: 0 0 15px #00ff41;
        margin-bottom: 25px;
    }
    .stFileUploader section { background-color: #161b22 !important; border: 1px dashed #00ff41 !important; }
    .stChatMessage { border: 1px solid #1f2937; border-radius: 10px; margin-bottom: 10px; }
    </style>
    """, unsafe_allow_html=True)

# عرض اسم المطور في الأعلى
st.markdown("<h1 class='dev-name'>المطور: محمد محمود صويلح 🛠️</h1>", unsafe_allow_html=True)

# --- 2. وظيفة إنشاء تقرير PDF (النسخة المصححة) ---
def generate_pdf(messages):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Cyber Security Analysis Report", ln=True, align='C')
    pdf.set_font("Helvetica", "I", 10)
    
    current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    pdf.cell(0, 10, f"Generated by: Cyber Guard Pro (Dev: M.M. Swailah) - {current_time}", ln=True, align='C')
    pdf.ln(10)
    
    for msg in messages:
        if msg["role"] == "system": continue
        role = "USER" if msg["role"] == "user" else "AI ASSISTANT"
        
        # تنسيق الدور (User/AI)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"{role}:", ln=True)
        
        # تنسيق المحتوى وتجنب أخطاء الترميز
        pdf.set_font("Helvetica", "", 10)
        content = msg["content"].encode('latin-1', 'ignore').decode('latin-1')
        pdf.multi_cell(0, 8, content)
        pdf.ln(4)
    
    return pdf.output() # يعيد bytes مباشرة في الإصدارات الجديدة

# --- 3. القائمة الجانبية وإعدادات النموذج ---
st.sidebar.title("⚙️ التحكم والتقارير")
model_choice = st.sidebar.selectbox(
    "المحرك المتاح:", 
    ("gpt-4o", "gpt-4", "gemini", "llama-3-70b", "blackboxai")
)

# تهيئة سجل المحادثة
if "messages" not in st.session_state:
    st.session_state.messages = [{"role": "system", "content": "You are a Cyber Security Expert. Analyze files and provide security insights."}]

# زر تحميل التقرير (يظهر فقط إذا بدأت المحادثة)
if len(st.session_state.messages) > 1:
    try:
        pdf_data = generate_pdf(st.session_state.messages)
        st.sidebar.download_button(
            label="📥 تحميل تقرير التحليل (PDF)",
            data=pdf_data,
            file_name=f"Cyber_Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M')}.pdf",
            mime="application/pdf"
        )
    except Exception as e:
        st.sidebar.error("فشل تجهيز ملف PDF")

if st.sidebar.button("🗑️ مسح السجل"):
    st.session_state.messages = []
    st.rerun()

# --- 4. واجهة المحادثة الرئيسية ---
for message in st.session_state.messages:
    if message["role"] != "system":
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

# منطقة رفع الملفات (📎) فوق شريط الأوامر
with st.container():
    uploaded_file = st.file_uploader("📎 أرفق ملفاً للتحليل (أكواد أو صور)", type=["txt", "py", "js", "jpg", "png"], label_visibility="collapsed")
    if uploaded_file:
        st.success(f"📁 تم اكتشاف الملف: {uploaded_file.name}")

# استقبال أوامر المستخدم
if prompt := st.chat_input("أدخل أمر التحليل السيبراني هنا..."):
    
    # تحضير النص النهائي (دمج الملف إن وجد)
    final_prompt = prompt
    if uploaded_file:
        final_prompt = f"Context: The user uploaded a file named {uploaded_file.name}. Question: {prompt}"

    # إضافة سؤال المستخدم
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # إنشاء رد الذكاء الاصطناعي
    with st.chat_message("assistant"):
        message_placeholder = st.empty()
        full_response = ""
        try:
            client = Client()
            response = client.chat.completions.create(
                model=model_choice,
                messages=[{"role": "user", "content": final_prompt}],
                stream=True,
            )
            for chunk in response:
                if chunk.choices[0].delta.content:
                    full_response += chunk.choices[0].delta.content
                    message_placeholder.markdown(full_response + " 🟢")
            
            message_placeholder.markdown(full_response)
            st.session_state.messages.append({"role": "assistant", "content": full_response})
            st.rerun() # لإظهار زر التحميل في القائمة الجانبية فوراً
            
        except Exception as e:
            st.error(f"⚠️ خطأ في الاتصال بالمحرك. حاول اختيار نموذج آخر.")
