import streamlit as st
from g4f.client import Client
from fpdf import FPDF
import datetime

# --- 1. إعدادات الصفحة والواجهة السيبرانية ---
st.set_page_config(page_title="Cyber Guard Pro", page_icon="🛡️", layout="wide")

st.markdown("""
    <style>
    .stApp { background-color: #0d1117; color: #00ff41; }
    .dev-name { 
        text-align: center; font-family: 'Courier New'; color: #00ff41; 
        border-bottom: 2px solid #00ff41; padding: 10px; text-shadow: 0 0 15px #00ff41;
    }
    .stFileUploader section { background-color: #161b22 !important; border: 1px dashed #00ff41 !important; }
    </style>
    """, unsafe_allow_html=True)

st.markdown("<h1 class='dev-name'>المطور: محمد محمود صويلح 🛠️</h1>", unsafe_allow_html=True)

# --- 2. وظيفة إنشاء تقرير PDF ---
def generate_pdf(messages):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Cyber Security Analysis Report", ln=True, align='C')
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 10, f"Generated by: Cyber Guard Pro (Dev: M.M. Swailah) - {datetime.datetime.now()}", ln=True, align='C')
    pdf.ln(10)
    
    for msg in messages:
        if msg["role"] == "system": continue
        role = "USER" if msg["role"] == "user" else "AI ASSISTANT"
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, f"{role}:", ln=True)
        pdf.set_font("Helvetica", "", 10)
        # تنظيف النص من الرموز التي قد لا تدعمها المكتبة الافتراضية
        clean_text = msg["content"].encode('latin-1', 'ignore').decode('latin-1')
        pdf.multi_cell(0, 10, clean_text)
        pdf.ln(5)
    
    return pdf.output(dest='S').encode('latin-1')

# --- 3. القائمة الجانبية ---
st.sidebar.title("⚙️ التحكم والتقارير")
model_choice = st.sidebar.selectbox("المحرك:", ("gpt-4", "gpt-3.5-turbo", "gemini", "llama-3-70b", "blackboxai"))

if "messages" not in st.session_state:
    st.session_state.messages = [{"role": "system", "content": "You are a Cyber Security Expert. Assist with analysis and protection."}]

# زر تحميل التقرير
if len(st.session_state.messages) > 1:
    pdf_data = generate_pdf(st.session_state.messages)
    st.sidebar.download_button(
        label="📥 تحميل تقرير التحليل (PDF)",
        data=pdf_data,
        file_name="cyber_analysis_report.pdf",
        mime="application/pdf"
    )

if st.sidebar.button("🗑️ مسح السجل"):
    st.session_state.messages = []
    st.rerun()

# --- 4. واجهة المحادثة ورفع الملفات ---
for message in st.session_state.messages:
    if message["role"] != "system":
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

with st.container():
    uploaded_file = st.file_uploader("📎 أرفق ملفاً (أكواد أو صور)", type=["txt", "py", "js", "jpg", "png"], label_visibility="collapsed")
    if uploaded_file: st.info(f"📁 ملف مكتشف: {uploaded_file.name}")

if prompt := st.chat_input("أدخل أمر التحليل..."):
    final_prompt = prompt
    if uploaded_file:
        final_prompt = f"File: {uploaded_file.name}. Question: {prompt}"

    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"): st.markdown(prompt)

    with st.chat_message("assistant"):
        message_placeholder = st.empty()
        full_response = ""
        try:
            client = Client()
            response = client.chat.completions.create(
                model=model_choice,
                messages=[{"role": "user", "content": final_prompt}],
                stream=True,
            )
            for chunk in response:
                if chunk.choices[0].delta.content:
                    full_response += chunk.choices[0].delta.content
                    message_placeholder.markdown(full_response + " 🟢")
            message_placeholder.markdown(full_response)
            st.session_state.messages.append({"role": "assistant", "content": full_response})
            st.rerun() # لإظهار زر التحميل فوراً بعد الرد
        except Exception:
            st.error("⚠️ فشل الاتصال بالنموذج.")
